Rollback of PR #51903 Rollback #51903, because Windows Builds fail with error - tensorflow/core/kernels/mkl/mkl_layer_norm_op.cc(95): error C2398: Element '1': conversion from 'size_t' to 'ptrdiff_t' requires a narrowing tensorflow/core/kernels/mkl/mkl_layer_norm_op.cc(99): error C2398: Element '1': conversion from 'size_t' to 'ptrdiff_t' requires a narrowing conversion
tensorflow/core/kernels/mkl/mkl_layer_norm_op.cc(113): error C2036: 'void *': unknown size

PiperOrigin-RevId: 417311855
Change-Id: If67329113ed6d7caf7915e6fe89fcc7aeea02c1b