Fix CMAKE build issue on Linux (#20122)
* Fix CMAKE build issue on Linux

While building tensorflow on Linux with CMAKE, as specified in README:
```
tensorflow/tools/ci_build/ci_build.sh CMAKE tensorflow/tools/ci_build/builds/cmake.sh
```

The following build error happens:
```
CMakeFiles/tf_core_lib.dir/workspace/tensorflow/core/platform/cloud/curl_http_request.cc.o: In function `tensorflow::CurlHttpRequest::~CurlHttpRequest()':
curl_http_request.cc:(.text+0x11b): undefined reference to `curl_slist_free_all'
curl_http_request.cc:(.text+0x146): undefined reference to `curl_slist_free_all'
curl_http_request.cc:(.text+0x180): undefined reference to `curl_easy_cleanup'
...
```

There were several issues related. The file above requires curl which
was never supported on CMAKE at the first places.

This fix address the issue so that CMAKE build works on Linux.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

* Update boringssl so that it is synced up with the version used in bazel

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

* Add tensorflow_ENABLE_GCS_SUPPORT to control cloud platform files

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

* Use tensorflow_ENABLE_GCS_SUPPORT to control contrib/cloud on/off

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

* Remove tensorflow_ENABLE_GCS_SUPPORT

As GCS requires curl so it is not possible to have GCS
support now.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>