Fix ImportError: cannot import name 'dense_features'. This module was added to tf-estimator-nightly. Change the nightly build to depend on tf-estimator-nightly instead of tensorflow-estimator.
PiperOrigin-RevId: 313477121
Change-Id: Ia5eab6b0542789ba41dc691118a22c7e64b13258