fixed calling Estimator '_distribution' method
The code is calling a '_distribution' method which no longer exists.  It will produce error message <AttributeError: 'Estimator' object has no attribute '_distribution'> when training mirrored strategy with hooks.   

Changing '_distribution' to '_train_distribution' can fix the issue.