Work around the following bug in python 3.8
OverflowError: Python int too large to convert to C long

On windows, sizeof(long) is 4 bytes. Therefore, the large integers seem to be a problem when backed by some numpy types:
https://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma

PiperOrigin-RevId: 301407257
Change-Id: Ic0f7379eee360ff053283742f6495c1974b2c5e4