[mlir/tensorflow] Fix windows build
Error fixed: error C2039: 'isdigit': is not a member of 'std'
The error is caused by CL/272736262

PiperOrigin-RevId: 272908841