The behavior of outer_dimensions was different than before when the selected indices had a 0. Making it emulate the old behavior because gather stopped working for length 0 Tensors.
e.g.: Gathering row 1 from a Tensor of shape [2, 0] should result in a [1, 0] Tensor, but instead resulted in an error like:
AttributeError: index 1 is not in [0, 2)
Change: 119998790