Fix nightly test failures.
Default value of "allow_pickle" is changed to "False" in NumPy 1.16.3 so we are seeing the following error with latest version of Numpy:
ValueError: Object arrays cannot be loaded when allow_pickle=False
PiperOrigin-RevId: 244863400