Enable ruy optimizations in a less error-prone way.
http://cl/248452685 ended up reverting a #include of opt_set.h in common.h, which disabled prefetching, since `#if RUY_OPT_SET & RUY_OPT_PREFETCH` is still true even if those macros aren't defined.

That is, this is not a compilation error:

```
#if UNDEFINED_MACRO_FOO & UNDEFINED_MACRO_BAR
#error "this is never reached"
#else
#endif
```

This CL replaces `RUY_OPT_SET & RUY_OPT_*` with a less error-prone `RUY_ENABLE_OPTIMIZATION(RUY_OPT_*)`, which is a compile error if RUY_ENABLE_OPTIMIZATION isn't defined.

PiperOrigin-RevId: 252468543