Disable complex training ops on Windows
It seems the complex training ops are causing the following
compiler error:

eigen\cxx11\src\tensor\tensorexpr.h(209) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'd:\agent\_work\2\s\src\vctools\compiler\utc\src\p2\main.c', line 187)

PiperOrigin-RevId: 278054608
Change-Id: I6eee97668e1377fbccda409a6311229c656ca0e3