#tf-nightly Disable nightly build of broken tests.
Caused by https://github.com/tensorflow/tensorflow/commit/0471665c9a294e9753437c01944bb620ea560a8a. Error message:

```
2022-06-30 10:24:44.114729: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/fbac33eb30dbfb6b11b15a7ff5ac830d/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/compiler/mlir/quantization/tensorflow/python/concurrency_test.runfiles/org_tensorflow/tensorflow/compiler/mlir/quantization/tensorflow/python/integration_test/concurrency_test.py", line 23, in <module>
    from tensorflow.compiler.mlir.quantization.tensorflow.python import quantize_model
  File "/root/.cache/bazel/_bazel_root/fbac33eb30dbfb6b11b15a7ff5ac830d/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/compiler/mlir/quantization/tensorflow/python/concurrency_test.runfiles/org_tensorflow/tensorflow/compiler/mlir/quantization/tensorflow/python/quantize_model.py", line 29, in <module>
    from tensorflow.compiler.mlir.quantization.tensorflow.python import representative_dataset as repr_dataset
  File "/root/.cache/bazel/_bazel_root/fbac33eb30dbfb6b11b15a7ff5ac830d/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/compiler/mlir/quantization/tensorflow/python/concurrency_test.runfiles/org_tensorflow/tensorflow/compiler/mlir/quantization/tensorflow/python/representative_dataset.py", line 25, in <module>
    RepresentativeSample = Mapping[str, core.TensorLike]
TypeError: 'ABCMeta' object is not subscriptable
```
PiperOrigin-RevId: 458334698