Fix variable handle input shape in function deserialization.
Previously, it was using the _input_shape attribute, but this always returned a scalar shape for resource handles, causing shape inference errors like:

```
ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [?,2,2]
 and params shape: [] for '{{node lookup/lookup_call}} =
ResourceGatherNd[Tindices=DT_INT32, _output_shapes=[[?,2]], dtype=DT_FLOAT]
(lookup_lookup_call_resource:0, inputs:0)' with input shapes: [], [?,2,2].
```
PiperOrigin-RevId: 424144483
Change-Id: I283c109a3502a0ecf3984ff57fa3f74d4508e612