Workaround FlatMap windows build breakage.
Windows builds break on the following simplified example:

  template <typename Key, ...>
  class FlatSet {
   public:
    typedef Key value_type;

    class const_iterator {
     public:
      typedef FlatSet::value_type value_type;  // Fails on windows
    };
  };

The build succeeds by adding 'typename':
      typedef typename FlatSet::value_type value_type;  // OK on windows

<simplified log of compiler error>
flatmap.h(110): warning C4346: 'difference_type': dependent name is not a type (compiling source file ...cancellation.cc)

flatmap.h(110): note: prefix with 'typename' to indicate a type (compiling source file ...cancellation.cc)

flatmap.h(161): note: see reference to class template instantiation 'tensorflow::gtl::FlatMap<Key,Val,Hash,Eq>::iterator' being compiled (compiling source file ...cancellation.cc)

flatmap.h(376): note: see reference to class template instantiation 'tensorflow::gtl::FlatMap<Key,Val,Hash,Eq>' being compiled (compiling source file ...cancellation.cc)

flatmap.h(110): error C2061: syntax error: identifier 'difference_type' (compiling source file ...cancellation.cc)
</simplified log of compiler error>

This is a bug in the windows compiler. It is true that FlatSet::value_type is a
dependent name, but it also refers to the "current instantiation", so 'typename'
shouldn't be required.  For details see:
http://en.cppreference.com/w/cpp/language/dependent_name#Current_instantiation

But it doesn't hurt to add typename; it is simply redundant.
Change: 147776071