Fix build failure with CUDA 11.2.0.
A symbol was used that was only included starting in CUDA 11.2.1, which has cuSPARSE 11.4. The error was:

    error: 'cusparseSDDMMAlg_t' has not been declared

PiperOrigin-RevId: 372399604
Change-Id: I2459a266896943cd6ee67253e133a9d2cba8f7fe