[tf nightly] Fix macos build.
Error message:
error: /Applications/Xcode_10.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no output file specified (specify with -o output)

Don't use Xcode 10.3 for the macos nightly build.

Xcode 10.3 is very old and no longer works with Bazel 4.x.

PiperOrigin-RevId: 414630446
Change-Id: I7f29bb73ff1078d8fac47f3d56fd45c5cf285098