Update googletest to fix a test compilation error. Only updating to the commit that has the fix (August 2019) instead of the latest commit because the latest commit needs some TF code changes to work with it.
The error message:
```
$ bazel build --config=opt //tensorflow/core/tpu/kernels:sharding_util_ops_test
...
ERROR: tensorflow/core/tpu/kernels/BUILD:1071:11: C++ compilation of rule '//tensorflow/core/tpu/kernels:sharding_util_ops_test' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 196 argument(s) skipped)
In file included from external/com_google_googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
                 from external/com_google_googletest/googletest/include/gtest/gtest.h:60,
                 from ./tensorflow/core/platform/test.h:26,
                 from ./tensorflow/core/framework/tensor_testutil.h:24,
                 from tensorflow/core/tpu/kernels/sharding_util_ops_test.cc:28:
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h: In instantiation of 'struct testing::internal::IteratorTraits<tensorflow::{anonymous}::XlaSplitNDTestParam>':
external/com_google_googletest/googletest/include/gtest/gtest-param-test.h:301:1:   required by substitution of 'template<class ForwardIterator> testing::internal::ParamGenerator<typename testing::internal::IteratorTraits<Iterator>::value_type> testing::ValuesIn(ForwardIterator, ForwardIterator) [with ForwardIterator = tensorflow::{anonymous}::XlaSplitNDTestParam]'
tensorflow/core/tpu/kernels/sharding_util_ops_test.cc:515:1:   required from here
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h:1967:41: error: no type named 'value_type' in 'struct tensorflow::{anonymous}::XlaSplitNDTestParam'
   typedef typename Iterator::value_type value_type;
                                         ^~~~~~~~~~
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h: In instantiation of 'struct testing::internal::IteratorTraits<tensorflow::{anonymous}::RankedXlaSplitNDTestParam>':
external/com_google_googletest/googletest/include/gtest/gtest-param-test.h:301:1:   required by substitution of 'template<class ForwardIterator> testing::internal::ParamGenerator<typename testing::internal::IteratorTraits<Iterator>::value_type> testing::ValuesIn(ForwardIterator, ForwardIterator) [with ForwardIterator = tensorflow::{anonymous}::RankedXlaSplitNDTestParam]'
tensorflow/core/tpu/kernels/sharding_util_ops_test.cc:560:1:   required from here
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h:1967:41: error: no type named 'value_type' in 'struct tensorflow::{anonymous}::RankedXlaSplitNDTestParam'
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h: In instantiation of 'struct testing::internal::IteratorTraits<tensorflow::{anonymous}::XlaConcatNDTestParam>':
external/com_google_googletest/googletest/include/gtest/gtest-param-test.h:301:1:   required by substitution of 'template<class ForwardIterator> testing::internal::ParamGenerator<typename testing::internal::IteratorTraits<Iterator>::value_type> testing::ValuesIn(ForwardIterator, ForwardIterator) [with ForwardIterator = tensorflow::{anonymous}::XlaConcatNDTestParam]'
tensorflow/core/tpu/kernels/sharding_util_ops_test.cc:1139:1:   required from here
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h:1967:41: error: no type named 'value_type' in 'struct tensorflow::{anonymous}::XlaConcatNDTestParam'
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h: In instantiation of 'struct testing::internal::IteratorTraits<tensorflow::{anonymous}::RankedXlaConcatNDTestParam>':
external/com_google_googletest/googletest/include/gtest/gtest-param-test.h:301:1:   required by substitution of 'template<class ForwardIterator> testing::internal::ParamGenerator<typename testing::internal::IteratorTraits<Iterator>::value_type> testing::ValuesIn(ForwardIterator, ForwardIterator) [with ForwardIterator = tensorflow::{anonymous}::RankedXlaConcatNDTestParam]'
tensorflow/core/tpu/kernels/sharding_util_ops_test.cc:1186:1:   required from here
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h:1967:41: error: no type named 'value_type' in 'struct tensorflow::{anonymous}::RankedXlaConcatNDTestParam'
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h: In instantiation of 'struct testing::internal::IteratorTraits<tensorflow::{anonymous}::RoundtripXlaSplitConcatNDTestParam>':
external/com_google_googletest/googletest/include/gtest/gtest-param-test.h:301:1:   required by substitution of 'template<class ForwardIterator> testing::internal::ParamGenerator<typename testing::internal::IteratorTraits<Iterator>::value_type> testing::ValuesIn(ForwardIterator, ForwardIterator) [with ForwardIterator = tensorflow::{anonymous}::RoundtripXlaSplitConcatNDTestParam]'
tensorflow/core/tpu/kernels/sharding_util_ops_test.cc:1422:1:   required from here
external/com_google_googletest/googletest/include/gtest/internal/gtest-port.h:1967:41: error: no type named 'value_type' in 'struct tensorflow::{anonymous}::RoundtripXlaSplitConcatNDTestParam'
Target //tensorflow/core/tpu/kernels:sharding_util_ops_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 108.943s, Critical Path: 73.96s
INFO: 2434 processes: 416 internal, 2018 local.
FAILED: Build did NOT complete successfully
```

Credit: https://github.com/tensorflow/tensorflow/pull/50638
PiperOrigin-RevId: 385706716
Change-Id: Ib2ef51f92df1e786697f8ee39ef28d25af2822ab