Make TensorRT convert_nodes.cc C++11 conforming, fixing build under GCC 8.
GCC 8 (correctly) complains that lambdas are not literals and
therefore cannot be "constexpr" in C++11. Fix is trivial.

Elided GCC 8 diagnostics follow.

tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:3960:3: error: the type '...::<lambda(nvinfer1::ITensor*, bool)>' of 'constexpr' variable 'get_matrix_op' is not literal
   };
   ^
...because:
       [](nvinfer1::ITensor* in, bool transpose) -> nvinfer1::MatrixOperation {
        ^
cc1plus: note:   ...::<lambda(nvinfer1::ITensor*, bool)>' is a closure type, which is only literal in C++17 and later