Fix "does not depend on module" error when building `//tensorflow/core/common_runtime/eager:execute` with oneDNN.
Error message:
```
tensorflow/core/graph/mkl_graph_util.h:20:10: error: module //tensorflow/core/common_runtime/eager:execute does not depend on a module exporting 'absl/base/call_once.h'
```

PiperOrigin-RevId: 492663173