Fix race condition in EagerContext::AddFunction.
I've been seeing test flakes when running sharded tests:
```
InternalError: Function: __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:CPU:0 is in the cache but not in the library [Op:StridedSlice]
```

This error occurs when:
1.  Thread A acquires the `cache_mu_` lock.
2.  Thread A finds no function in the cache and so creates (and references) it.
3.  Thread A sets `is_first_ref = True`.
4.  Thread A releases the `cache_mu_` lock.
5.  Thread B acquires the `cache_mu_` lock.
6.  Thread B finds the function in the cache.
7.  Thread B doesn't find the function in the library. The error occurs.
8.  Thread A adds the function to the library.

Changes to fix this race condition:
1.  Do not release `cache_mu_` until the function has been added to the library.
2.  To avoid a similar race condition with RemoveFunction, do not release
    `cache_mu_` until the function is removed from the library.
3.  For efficiency, release `cache_mu_` before attempting remote registration.

PiperOrigin-RevId: 437055316